### ISSUE TITLE
类缺失 无法运行

### ISSUE THREAD

**Issue by TheoCreator** [WuLC/KeywordExtraction#3]
项目无法正常运行

com.hankcs.hanlp.或者com.lc.nlp包的类不存在，无法使用。
引入的第三方jar包也没有pom.xml文件。

**Comment by GabrielXie** [comment]
<dependency>                             
      <groupId>com.hankcs</groupId>        
      <artifactId>hanlp</artifactId>       
      <version>portable-1.7.4</version>    
  </dependency>
